### ISSUE TITLE
Custom Commands

### ISSUE THREAD

**Issue by bvanseg** [bvanseg/ccake#13]
**Is your feature request related to a problem? Please describe.**
CCake's existing function set is sound enough to be able to build a simple C/C++ project, but when it comes to more complex projects that may have more needs, CCake's existing set of commands is not sufficient to complete complex tasks.

**Describe the solution you'd like**
To allow for more complex projects, CCake can greatly benefit from **custom commands** that can be executed through a new command, such that the cli input looks like the following: `ccake run <custom-command-name>`.

These custom commands would be defined in the `ccake.toml` file like so:
```toml
[commands]
clean-build = "ccake build --clean"
install-build = "ccake install && ccake build"
# python and shell scripts should also be valid, not just ccake commands :)
```

**Describe alternatives you've considered**
N/A.

**Additional context**
N/A.
